### ISSUE TITLE
[Android] FATAL EXCEPTION: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by retyui** [react-native-text-input-mask/react-native-text-input-mask#150]
# Bug

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fixmi, PID: 22920
    java.lang.IndexOutOfBoundsException: setSpan (5 ... 5) ends beyond length 4
        at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
        at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:676)
        at android.text.Selection.setSelection(Selection.java:94)
        at android.text.Selection.setSelection(Selection.java:78)
        at android.text.Selection.setSelection(Selection.java:153)
        at android.widget.EditText.setSelection(EditText.java:136)
        at com.redmadrobot.inputmask.MaskedTextChangedListener.afterTextChanged(MaskedTextChangedListener.kt:176)
        at com.facebook.react.views.textinput.ReactEditText$TextWatcherDelegator.afterTextChanged(ReactEditText.java:751)
        at android.widget.TextView.sendAfterTextChanged(TextView.java:10551)
        at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13388)
        at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
        at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
        at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:37)
        at android.view.inputmethod.BaseInputConnection.deleteSurroundingText(BaseInputConnection.java:250)
        at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:450)
        at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:89)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

## Environment info

React native info output:

```bash
System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 507.65 MB / 15.51 GB
    Shell: 3.0.2 - /usr/bin/fish
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.17.3 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

Library version: 2.0.0

## Steps To Reproduce

1. create a new app `react-native init bugRNTIM`
2. Update an App.js file (see `Reproducible sample code`)
3. Fill the text input
 
![image](https://user-images.githubusercontent.com/4661784/72671979-0861f700-3a64-11ea-8a0a-5f2cefcac50e.png)

4. Then press a 'setMask' button to set a short mask
5. Finally focus text field and input any number
6. Crash :(

## Describe what you expected to happen:

After mask property updating value should be truncated and application does not crash on input

## Reproducible sample code

```js
import React, {useState} from 'react';
import {View, Text, Button} from 'react-native';
import TextInputMask from 'react-native-text-input-mask';

export default () => {
  const [mask, setMask] = useState('+1[0000]');

  return (
    <View>
      <Text>{mask}</Text>
      <TextInputMask
        onChangeText={(formatted, extracted) => {
          console.log(' --- xdebug ', {formatted, extracted});
        }}
        mask={mask}
      />
      <Button
        title={'setMask'}
        onPress={() => {
          setMask('+1[00]');
        }}
      />
    </View>
  );
};
```

**Comment by retyui** [comment]
Fixed in https://github.com/react-native-community/react-native-text-input-mask/pull/149/commits/c5df7495514c1e19bcd0e05295e2fddf88ebd616
