### ISSUE TITLE
Android ReactTextInputShadowNode.java and ReactEditText.java

### ISSUE THREAD

**Issue by fatihyildizhan** [react-native-text-input-mask/react-native-text-input-mask#232]
App crashes when I type phone number.

```
package.json:
"react": "16.13.1",
"react-native": "^0.63.4",
"react-native-text-input-mask": "^3.1.4"
```

`mask="[000]-[000]-[00]-[00]"

keyboardType="phone-pad"
`

`com.facebook.react.views.textinput.ReactTextInputShadowNode.createInternalEditText:`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:880)
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1163)
       at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:434)
       at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:259)
       at android.view.View.computeOpaqueFlags(View.java:19424)
       at android.view.View.setBackgroundDrawable(View.java:24701)
       at android.view.View.setBackground(View.java:24594)
       at android.view.View.<init>(View.java:6191)
       at android.widget.TextView.<init>(TextView.java:1223)
       at android.widget.EditText.<init>(EditText.java:106)
       at android.widget.EditText.<init>(EditText.java:102)
       at android.widget.EditText.<init>(EditText.java:98)
       at android.widget.EditText.<init>(EditText.java:94)
       at com.facebook.react.views.textinput.ReactTextInputShadowNode.createInternalEditText(ReactTextInputShadowNode.java:265)
       at com.facebook.react.views.textinput.ReactTextInputShadowNode.setThemedContext(ReactTextInputShadowNode.java:85)
```

`com.facebook.react.views.textinput.ReactEditText.<init>`

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.createAllFutures(DrawableContainer.java:880)
       at android.graphics.drawable.DrawableContainer$DrawableContainerState.getOpacity(DrawableContainer.java:1163)
       at android.graphics.drawable.DrawableContainer.getOpacity(DrawableContainer.java:434)
       at android.graphics.drawable.InsetDrawable.getOpacity(InsetDrawable.java:259)
       at android.view.View.computeOpaqueFlags(View.java:19424)
       at android.view.View.setBackgroundDrawable(View.java:24701)
       at androidx.appcompat.widget.AppCompatEditText.setBackgroundDrawable(AppCompatEditText.java:109)
       at android.view.View.setBackground(View.java:24594)
       at android.view.View.<init>(View.java:6191)
       at android.widget.TextView.<init>(TextView.java:1223)
       at android.widget.EditText.<init>(EditText.java:106)
       at android.widget.EditText.<init>(EditText.java:102)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:73)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:69)
       at androidx.appcompat.widget.AppCompatEditText.<init>(AppCompatEditText.java:65)
       at com.facebook.react.views.textinput.ReactEditText.<init>(ReactEditText.java:111)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:128)
       at com.facebook.react.views.textinput.ReactTextInputManager.createViewInstance(ReactTextInputManager.java:84)
```

**Comment by marla-singer** [comment]
@fatihyildizhan check out that

**Issue**: https://github.com/facebook/react-native/issues/17530
**PR**: https://github.com/facebook/react-native/pull/29452

**Solution:** 
1) create a new file edit_text.xml: https://github.com/facebook/react-native/pull/29452/files#diff-8b03a3f8d7a1a124748ad859c0d965f2be9a61672a637092ca05d9348122e0df

2) update the file styles.xml: https://github.com/facebook/react-native/pull/29452/files#diff-b58456179833a11ee63ae971c033a77701fba85f5b0bd8e2706dd3c0a691da74
