### ISSUE TITLE
React native input mask testing with jest

### ISSUE THREAD

**Issue by ankiii16** [react-native-text-input-mask/react-native-text-input-mask#234]
Even after mocking the react-native-text-input-mask. I am getting following error. Please help make out here I am not performing any operations from test suite just rendering the screen.
<img width="1792" alt="Screen Shot 2021-05-31 at 8 24 52 pm" src="https://user-images.githubusercontent.com/40176565/120180675-66edd680-c24f-11eb-871e-32ee30c2b230.png">
<img width="1792" alt="Screen Shot 2021-05-31 at 8 33 28 pm" src="https://user-images.githubusercontent.com/40176565/120180749-7f5df100-c24f-11eb-97fc-b71ca12bb766.png">

**Comment by martintreurnicht** [comment]
Not sure what the issue is here, could be related to how you're using it. I'd try just using it directly without the wrapping TextInput component

**Comment by oemremolla** [comment]
Hi , I had the same issue. I solved the problem by following the steps in this issue. #17 . You can mock Input like that.

`class TextInputMask extends React.Component {
  render() {
    return <Input />;
  }
}`

**Comment by NathHorrigan** [comment]
Fairly sure this is because the masking is done natively in Swift or Java which will not run during a Jest test since it is running in a fake environment.

**Comment by MikePolen** [comment]
I created a brand new react native project and all I added was TextInputMask, jest and the min requirements to get it to run.

When I run the one unit test:
`import React from 'react'; 
import { render } from "@testing-library/react-native";
import TextInputMask from 'react-native-text-input-mask';

jest.mock("react-native-text-input-mask", () => ({
  default: jest.fn(),
}));

describe("test", ()=> {
    it("works", ()=> {
        const { toJSON } = render(
            <TextInputMask
              onChangeText={(formatted, extracted) => {
                console.log(formatted) // +1 (123) 456-78-90
                console.log(extracted) // 1234567890
              }}
              mask={"+1 ([000]) [000] [00] [00]"}
          /> 
          );
          expect(toJSON).toMatchSnapshot();
    })
});
`
I get
`    Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at createFiberFromTypeAndProps (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16180:21)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:16208:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5358:23)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5418:35)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7991:28)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8547:5)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9994:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13800:12)
      at workLoopSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13728:5)
      at renderRootSync (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13691:7)
`
The package.json is
`{
  "name": "my-project",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "@testing-library/react-native": "^9.0.0",
    "@types/jest": "^27.4.1",
    "expo": "~44.0.2",
    "expo-splash-screen": "~0.14.1",
    "expo-status-bar": "~1.2.0",
    "jest": "^27.5.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-native": "0.64.3",
    "react-native-text-input-mask": "^3.1.4",
    "react-native-web": "0.17.1",
    "react-test-renderer": "^17.0.2",
    "ts-jest": "^27.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9"
  },
  "private": true
}`

What do I have to do to get this simple unit test to work?

**Comment by cgarate** [comment]
@MikePolen I was struggling with this and tried a bunch of solutions until I ran into this in the Jest docs: https://jestjs.io/docs/tutorial-react-native#mock-native-modules-using-jestmock
So I just added the following mock to my `jest.setup.js` file: `jest.mock('react-native-text-input-mask', () => 'TextInputMask')`
It worked like a charm on my end. Hope it helps.

**Comment by samianc** [comment]
I'm using input method instead of change and it's working.

`
  const inputInstance: any = screen.getByTestId('heightInput');

  expect(inputInstance.value).toBe('');
  await fireEvent.input(inputInstance, {
    target: { value: '178' }
  });
  expect(inputInstance.value).toBe('1.78');`

**Comment by kaanoner3** [comment]
In my case, the `extracted` value in `onChangeText` is always undefined in Jest. What is the proper way of mocking this library?
