### ISSUE TITLE
React Native Input Mask setMask got 3 arguments, expected 2

### ISSUE THREAD

**Issue by SaulNunez** [react-native-text-input-mask/react-native-text-input-mask#250]
I'm having a bit of a time trying to wrap my head around this.

At first I checked if something is wrong with my mask, However, I've checked the RedMadRobot's documentation, and I've removed $ the money symbol, and tried with mask '[0...]{.}[00]'. With less than stellar luck (same error).

This is my code more or less, I'm using typescript, this is that minus type definitions:
```
import React from 'react';
import {TextInput} from 'react-native-paper';
import TextInputMask from 'react-native-text-input-mask'; 

export default function MoneyInput(mainProps){
return (
    <TextInput
      mode="outlined"
      label="Costo"
      placeholder="00.00"
      render={(props) => <TextInputMask
        mask={'$[0...].[00]'}
        {...props}
      />}
      {...mainProps} />
  );
}
```

I'm using React Native Paper, that recomends using React Native Input Mask by passing it like this.

`'react-native-text-input-mask'` version is: 3.1.4

I'm getting this error:
```
2021-07-05 16:27:26.481 28137-31526/com.example E/unknown:ReactNative: Exception in native call
    com.facebook.react.bridge.NativeArgumentsParseException: RNTextInputMask.setMask got 3 arguments, expected 2
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by lamas250** [comment]
did you have any success?

I had the same problem

**Comment by HaffASE** [comment]
remove previous version and clean anroid
`build cd android && ./gradlew clean`
